### PR TITLE
Cc2538 bsl dependency (needed for firefly)

### PR DESCRIPTION
**Pull request by rienafairefr**
First tests writing yocto bitbake images

### CODE REVIEW

**Comment by fsaintma** [comment]
I fix bitbake recipes errors and include them in gateway image. I have tested Yocto build on my laptop and now we should test on servers. I push the build image file iotlab-image-gateway-var-som-am35-20170929140503.rootfs.tar.gz on devlille. We view that next week.

**Comment by rienafairefr** [comment]
Thanks Frédéric !

**Comment by fsaintma** [comment]
@rienafairefr,  I put a new image on devlille (iotlab-image-gateway-var-som-am35-20171003094443.rootfs.tar.gz) with python-magic, cc2538 bsl script and update-rc.d fix. So can we test it on devllile and flirefy board and after merge this pull request

**Comment by rienafairefr** [comment]
I can say the update-rc.d fix is working, just pushed that image to devlille. 

Now it's missing the usermod command (setup.py release fails to find it when doing a ```usermod -a -G dialout www-data```). It's kinda weird because I see that command used in `meta-iotlab/recipes-support/gateway-code/gateway-code_git.bb` in pkg_postinst. I'd rank that really not critical (the user should already be in dialout group anyway when doing the `fab -f integration_fabfile.py release`)

**Comment by fsaintma** [comment]
@rienafairefr new image with usermod on devlille iotlab-image-gateway-var-som-am35-20171003120456.rootfs.tar.gz
It's the same problem like update-rc.d. I just remove opkg shadow (eg. usermod) package from an internal poky remove list

**Comment by rienafairefr** [comment]
Hum, I talked too fast with usermod. I had removed the add_www_data_to_dialout command in the setup.py so usermod was not called in my tests. Booting image is iotlab-image-gateway-var-som-am35-20171003094443 and usermod is not in the image :-/ Sorry

**Comment by rienafairefr** [comment]
disregard previous comment, usermod is there, I don't understand why it was not detected just before, did not reboot or anything

**Comment by fsaintma** [comment]
yes I have just notified you that I push  new version of gateway image on devllile which include usermod binary. The last one I hope :)

**Pull request merged**
