### PR TITLE
adding python-msp430-bsl telosb fork for tmotesky

### PR DESCRIPTION
**Pull request by rienafairefr**
bsl to flash tmotesky/telosb, from a fork on my repo from https://github.com/cetic/python-msp430-tools, maybe we'd put it somewhere else ?

### CODE REVIEW

**Comment by fsaintma** [comment]
Hi @rienafairefr 
I don't understand why you put your fork in the recipe SRC_URI ? Why you don't use the cetic directly ? 
You confirm me that you don't patch and commit anything in your fork ?

**Comment by rienafairefr** [comment]
Not patchign and commiting anything. You're right, I'll put the cetic github instead.

**Comment by rienafairefr** [comment]
fixed, I think

**Comment by fsaintma** [comment]
@rienafairefr I review your PR and I test build python-msp-430 package with success. Good job
Now you should just add this package in gateway package group : meta-iotlab/recipes-core/packagegroups/gateway-packagegroup.bb (eg. like cc2538-bsl)
After I merge it !!!

**Comment by rienafairefr** [comment]
OK, added the msp430-bsl to the package group.

**Pull request merged**
